version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: heirloom_postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgrespassword
      POSTGRES_DB: heirloom
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: heirloom_backend
    restart: always
    environment:
      PORT: 3001
      DATABASE_URL: "postgresql://postgres:postgrespassword@db:5432/heirloom?schema=public"
      JWT_SECRET: "heirloom-production-super-secret-key-salt"
      NODE_ENV: "production"
    ports:
      - "3001:3001"
      - "5555:5555"
    depends_on:
      - db

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: heirloom_frontend
    restart: always
    ports:
      - "3000:3000"
    environment:
      PORT: 3000
    depends_on:
      - backend

volumes:
  pgdata:
